name: Node.js CI

on:
  push:
    paths:
    - 'app/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./app
    - run: npm run build --if-present
      working-directory: ./app
    - run: npm test
      working-directory: ./app
      env:
        CI: true
